# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status_active:
        label: indikator.newsletter::lang.button.active
        type: checkbox
        conditions: status = 1

    status_inactive:
        label: indikator.newsletter::lang.button.inactive
        type: checkbox
        conditions: status = 2

    hidden:
        label: indikator.newsletter::lang.form.hidden
        type: checkbox
        conditions: hidden = 1

    created_date:
        label: indikator.newsletter::lang.form.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: indikator.newsletter::lang.form.updated_at
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
