# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status_final:
        label: indikator.newsletter::lang.form.status_final
        type: checkbox
        conditions: status = 1

    status_draft:
        label: indikator.newsletter::lang.form.status_draft
        type: checkbox
        conditions: status = 3

    last_send_at:
        label: indikator.newsletter::lang.form.last_send
        type: daterange
        conditions: last_send_at >= ':after' AND last_send_at <= ':before'

    created_date:
        label: indikator.newsletter::lang.form.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: indikator.newsletter::lang.form.updated_at
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
