# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status_active:
        label: indikator.newsletter::lang.form.status_active
        type: checkbox
        conditions: status = 1

    status_unsubscribed:
        label: indikator.newsletter::lang.form.status_unsubscribed
        type: checkbox
        conditions: status = 2

    status_pending:
        label: indikator.newsletter::lang.form.status_pending
        type: checkbox
        conditions: status = 3

    statistics:
        label: indikator.newsletter::lang.stat.mail
        type: numberrange
        conditions: statistics >= ':min' and statistics <= ':max'

    created_date:
        label: indikator.newsletter::lang.form.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: indikator.newsletter::lang.form.updated_at
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
