# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: indikator.newsletter::lang.menu.import
    modelClass: Indikator\Newsletter\Models\SubscribersImport
    list: $/indikator/newsletter/models/subscribersimport/columns.yaml
    redirect: indikator/newsletter/subscribers
    permissions: indikator.newsletter.import_export

export:
    title: indikator.newsletter::lang.menu.export
    modelClass: Indikator\Newsletter\Models\SubscribersExport
    list: $/indikator/newsletter/models/subscribersexport/columns.yaml
    redirect: indikator/newsletter/subscribers
    permissions: indikator.newsletter.import_export
    filename: subscribers.csv
